### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by jplatte** [t-b/cpp-copy-elision#1]
So, the last update is older than a year, I'm curious whether anything changed. Mind to do an update?

**Comment by t-b** [comment]
I'll see if I find some time.

**Comment by t-b** [comment]
I did an update and nothing changed at all. Which is quite sad from a technical POV.
The new PDF is available at http://www.byte-physics.de/cpp-copy-elision.html.

**Comment by jplatte** [comment]
Yeah, I agree. Thanks for the update though!
